<script setup lang="ts">
import { computed } from 'vue'
import { useSpoilerStore } from '@/stores/spoiler'
import { readableSize } from '@/lib/maths'
import { commonPrefix } from '@/lib/strings'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'

const TARGET_SIZE = Math.round(1024 * 1024 * 9.75)
const spoilerStore = useSpoilerStore()

const downloadEnabled = computed(() => spoilerStore.recordings.length > 0)

const formatRecordName = (name: string) => {
  if (name.endsWith('.aoe2record')) {
    name = name.substring(0, name.length - '.aoe2record'.length)
  }

  return `${name}_padded.aoe2record`
}

const paddedSize = computed(() => {
  if (spoilerStore.recordings.length == 0) {
    return 0
  }

  return Math.max(...spoilerStore.recordings.map((recording) => recording.size), TARGET_SIZE)
})

const padFile = (file: File, targetSize: number) => {
  if (file.size > targetSize) {
    return file
  }

  const suffixLen = targetSize - file.size
  const suffixArray = new Uint8Array(suffixLen).fill(0xaa)

  const dummyFile = new Blob([file, suffixArray, new Uint32Array([suffixLen]), 'AOE2_PAD'])
  return dummyFile
}

const downloadPadded = (file: File) => {
  console.log('download padded', file.size, paddedSize.value)
  const paddedRecording = padFile(file, paddedSize.value)
  return saveAs(paddedRecording, formatRecordName(file.name))
}

function downloadZip() {
  const zip = new JSZip()
  const zipComment = 'Generated by https://replaypacker.zeta-two.com'

  const targetSize = paddedSize.value

  for (const recording of spoilerStore.recordings) {
    const paddedRecording = padFile(recording, targetSize)
    zip.file(formatRecordName(recording.name), paddedRecording)
  }

  // TODO: This is a bit hacky but works for now
  let zipName =
    commonPrefix(spoilerStore.recordings.map((recording) => recording.name)) ||
    'padded-recordings.zip'
  if (zipName.endsWith('_G')) {
    zipName = zipName.substring(0, zipName.length - 2)
  }

  zip
    .generateAsync({
      type: 'blob',
      comment: zipComment,
      compression: 'DEFLATE',
      compressionOptions: {
        level: 6
      }
    })
    .then(function (blob) {
      saveAs(blob, zipName)
    })
}
</script>

<template>
  <div class="p-4 border-2 rounded-lg col-span-3 mt-4 mb-4">
    <table>
      <thead>
        <tr>
          <th class="border p-1">Name</th>
          <th class="border p-1">Size</th>
          <th class="border p-1">Padded size</th>
          <th class="border p-1"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="border p-1">All replays</td>
          <td class="border p-1"></td>
          <td class="border p-1"></td>
          <td class="border p-1">
            <button
              :disabled="!downloadEnabled"
              @click="downloadZip"
              class="btn text-1xl text-white dark:text-black"
              :class="{
                'bg-blue-500': downloadEnabled,
                'bg-blue-200': !downloadEnabled,
                'dark:bg-blue-700': downloadEnabled,
                'dark:bg-blue-300': !downloadEnabled
              }"
            >
              Download
            </button>
          </td>
        </tr>
        <tr v-for="recording in spoilerStore.recordings" v-bind:key="recording.name">
          <td class="border p-1">{{ formatRecordName(recording.name) }}</td>
          <td class="border p-1">{{ readableSize(recording.size) }}</td>
          <td class="border p-1">{{ readableSize(paddedSize) }}</td>
          <td class="border p-1">
            <button
              :disabled="!downloadEnabled"
              @click="downloadPadded(recording)"
              class="btn text-1xl text-white dark:text-black"
              :class="{
                'bg-blue-500': downloadEnabled,
                'bg-blue-200': !downloadEnabled,
                'dark:bg-blue-700': downloadEnabled,
                'dark:bg-blue-300': !downloadEnabled
              }"
            >
              Download
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
